### ISSUE TITLE
Does not compile for me

### ISSUE THREAD

**Issue by kohlerm** [src-d/hercules#2]
$ go version
go version go1.7.3 linux/amd64

$go install gopkg.in/src-d/hercules.v1/cmd/hercules
../hercules.v1/cmd/hercules/main.go:13:2: code in directory /home/kohlerm/go/src/gopkg.in/src-d/go-git.v4 expects import "srcd.works/go-git.v4"
 
removing the  import comment in doc.go
diff --git a/doc.go b/doc.go
index d304938..242f3be 100644
--- a/doc.go
+++ b/doc.go
@@ -34,4 +34,4 @@
 //             fmt.Println(commit)
 //         }
 //    }
-package git // import "srcd.works/go-git.v4"
+package git 

 ../../../github.com/fatih/color/color.go:21: undefined: isatty.IsCygwinTerminal
bash: ../../../github.com/fatih/color/color.go:21:: No such file or directory

Removing the IsCygwinTerminal call (I'm on linux)
$ go install gopkg.in/src-d/hercules.v1/cmd/hercules
gopkg.in/src-d/hercules.v1
../hercules.v1/analyser.go:66: cannot use blob (type *"srcd.works/go-git.v4/plumbing/object".Blob) as type *"gopkg.in/src-d/go-git.v4/plumbing/object".Blob in argument to loc
../hercules.v1/analyser.go:85: cannot use blob (type *"srcd.works/go-git.v4/plumbing/object".Blob) as type *"gopkg.in/src-d/go-git.v4/plumbing/object".Blob in argument to loc
../hercules.v1/analyser.go:107: cannot use blob_from (type *"srcd.works/go-git.v4/plumbing/object".Blob) as type *"gopkg.in/src-d/go-git.v4/plumbing/object".Blob in argument to str
../hercules.v1/analyser.go:108: cannot use blob_to (type *"srcd.works/go-git.v4/plumbing/object".Blob) as type *"gopkg.in/src-d/go-git.v4/plumbing/object".Blob in argument to str
../hercules.v1/analyser.go:213: cannot use commit (type *"srcd.works/go-git.v4/plumbing/object".Commit) as type *"gopkg.in/src-d/go-git.v4/plumbing/object".Commit in append
../hercules.v1/analyser.go:218: cannot use commit (type *"srcd.works/go-git.v4/plumbing/object".Commit) as type *"gopkg.in/src-d/go-git.v4/plumbing/object".Commit in append
../hercules.v1/analyser.go:310: cannot use prev_tree (type *"gopkg.in/src-d/go-git.v4/plumbing/object".Tree) as type *"srcd.works/go-git.v4/plumbing/object".Tree in argument to difftree.DiffTree
../hercules.v1/analyser.go:310: cannot use tree (type *"gopkg.in/src-d/go-git.v4/plumbing/object".Tree) as type *"srcd.works/go-git.v4/plumbing/object".Tree in argument to difftree.DiffTree

Any hints how to get it compiled?

**Comment by vmarkovtsev** [comment]
Yeah, I wrote this code when go-git v4 was under heavy development. The API changed since the last time. I summon @alcortesm since he was working on diff trees.

**Comment by alcortesm** [comment]
Yes, go-git v4 was, and still is, under development and its API changes frequently.

The best way to solve this problem would be to keep Hercules updated with go-git v4 (a moving target until we release it) or to port it to go-git v3 which is the current production ready version.

The errors you are seeing are caused by the fact that Hercules is importing `gopkg.in/src-d/go-git.v4` but that is no longer the import path of go-git v4, we changed that back on Jan 30 with go-gi v4 release candidate [rc8](https://github.com/src-d/go-git/releases/tag/v4.0.0-rc8) (commit [85a4efcc45312f022111907d82c5cc4ee3bdbb73](https://github.com/src-d/go-git/commit/85a4efcc45312f022111907d82c5cc4ee3bdbb73)).

Coincidentally, go-git v4 is going to get back to the old import path used by Hercules imminently, when we merge https://github.com/src-d/go-git/pull/303, and I think it will become the import path used in rc10, so this may get solved in a few hours by upgrading go-git once https://github.com/src-d/go-git/pull/303 has been merged.  Hercules may still have other issues though, as that is not the only change that has been introduced in go-git since Hercules was last updated.

**Comment by vmarkovtsev** [comment]
@kohlerm Sorry for such a long reaction

**Comment by kohlerm** [comment]
Thanks!
Unfortunately still does not work. 
Upgraded to go 1.8.1 and a new machine. 
I get
go get gopkg.in/src-d/hercules.v1/cmd/hercules
# gopkg.in/src-d/hercules.v1/cmd/hercules
cmd/hercules/main.go:37: repository.Commit undefined (type *git.Repository has no field or method Commit)
cmd/hercules/main.go:77: undefined: git.NewFilesystemRepository
cmd/hercules/main.go:82: undefined: git.NewMemoryRepository
cmd/hercules/main.go:85: repository.Clone undefined (type *git.Repository has no field or method Clone, but does have git.clone)
cmd/hercules/main.go:96: undefined: git.NewFilesystemRepository

**Comment by vmarkovtsev** [comment]
@kohlerm Please `got get` from scratch, because it is reported that it works in #3 and in [Travis](https://travis-ci.org/src-d/hercules)

**Comment by kohlerm** [comment]
ah ok strange, I tried a clean build with go 1.6 which failed. Then updated to go 1.8. now deleting everything, it works! 
Thanks!
